### ISSUE TITLE
Add feature section features to docs

### ISSUE THREAD

**Issue by MaxBenChrist** [blue-yonder/tsfresh#102]
many people do not seem to find the feature extraction module in our docs and ask about which features we extract.

The calculated features should be more easier to find in the docs

**Comment by earthgecko** [comment]
Hi @MaxBenChrist 

I am doing something similar that may be relevant here.  On may app side, tsfresh feature names are considered immutable once seen.  I was glad to see that 0.3.0 only added and did not change.  That said in my application I have to map tsfresh feature names to an id due to database relationships.

Further to this in my app tests, I test tsfresh, to ensure that the tsfresh version is calculating the exact same values and feature names by calculating the features of a known static timeseries.  Each version then has a baseline in the tests too.  That way if you guys do not think feature names should be immutable or decide to change one, it will be caught on the tests and I can assess what to do :)

All that said, on my side I have something similar that I wanted for all possible pytz timezones.  So I automatically build a .rst page in my documentation build that have contains all the possible pytz timeseries strings, as they are not easy to find for the user.

A similar applied method would probably suit here, considering that 0.3.0 added 9 more features than 0.1.2, it will save you having to update the docs manually all the time.

Further I am planning to do a pull request at some point to add PoC of the "test tsfresh always calculates the same values for the same features on a baseline timeseries" resources for your consideration.  They all work in my tests, I just need to port them into a tsfresh branch for you to have a look at.

It should not be too hard to get the feature names auto documented.  I am happy to look at it, at some point if you are are interested.  It probably will not be in the next week or 2, but it maybe be useful for future changes.

I am auto generating some py code that results in something like this and would be easy enough to auto generated .rst to docs:

```python
TSFRESH_VERSION = '0.3.0'
"""
:var TSFRESH_VERSION: The version of tsfresh installed by pip, this is important
    in terms of feature extraction baselines
:vartype TSFRESH_VERSION: str
"""

# TSFRESH_BASELINE_VERSION = '0.1.2'
TSFRESH_BASELINE_VERSION = '0.3.0'
"""
:var TSFRESH_BASELINE_VERSION: The version of tsfresh that was used to generate
    feature extraction baselines on.
:vartype TSFRESH_BASELINE_VERSION: str
"""

TSFRESH_FEATURES = [
    [1, 'value__symmetry_looking__r_0.65'],
    [2, 'value__mean_abs_change_quantiles__qh_1.0__ql_0.0'],
    [3, 'value__absolute_sum_of_changes'],
    [4, 'value__augmented_dickey_fuller'],
    [5, 'value__large_number_of_peaks__n_3'],
    [6, 'value__large_number_of_peaks__n_5'],
    [7, 'value__last_location_of_minimum'],
...
...
    [215, 'value__sample_entropy'],
    [216, 'value__sum_of_reoccurring_values'],
]
```

**Comment by MaxBenChrist** [comment]
Sounds interesting, indeed we are considering feature extractor names immutable. If we change them, we will consider this a non backwards compatible API change and increase the major version (we are following the semantic versioning http://semver.org)

I would be very interested to see a pr with your testing of "test tsfresh always calculates the same values for the same features on a baseline timeseries".

Regarding the docs, we are using sphinx autodoc to generate an overview over the feature extractor module.

**Comment by MaxBenChrist** [comment]
I think it is quite clear with the feature calculation section of our docs
