### ISSUE TITLE
TypeError: acf() got an unexpected keyword argument 'unbiased'

### ISSUE THREAD

**Issue by YWU99u** [blue-yonder/tsfresh#1045]
I faced this issue when I tried to use extract_features function from this package.This seemed to be an old, but I still could not figure out the solution for this problem. I've tried to downgrade my statsmodel to 0.12.1, but it turns out it gave me another error saying my pandas package had a compatibility issue as "ImportError: cannot import name 'Int64Index' from 'pandas'".
Does anyone have a solution on how to use this package?

**Comment by nils-braun** [comment]
Hi @YWU99u - which version of tsfresh, python and statsmodel are you using? Unfortunately, I can not reproduce this issue.

**Comment by XudongWang97** [comment]
I got the similar error, and I found the message showed file `feature_extraction/feature_calculators.py` different from current main branch.

Package versions:
python 3.7
tsfresh 0.20.1
statsmodels 0.13.2

Error message:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/opt/conda/lib/python3.7/site-packages/tsfresh/utilities/distribution.py", line 43, in _function_with_partly_reduce
    results = list(itertools. chain. from_ iterable(results))
  File "/opt/conda/lib/python3.7/site-packages/tsfresh/utilities/distribution.py", line 42, in <genexpr>
    results = (map_function(chunk, **kwargs) for chunk in chunk_list)
  File "/opt/conda/lib/python3.7/site-packages/tsfresh/feature_extraction/extraction.py", line 328, in _do_extraction_on_chunk
    return list(_f())
  File "/opt/conda/lib/python3.7/site-packages/tsfresh/feature_extraction/extraction.py", line 314, in _f
    result = func(x, param=parameter_list)
  File "/opt/conda/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 400, in agg_autocorrelation
    a = acf(x, unbiased=True, fft=n > THRESHOLD_TO_USE_FFT, nlags=max_maxlag)[1:]
TypeError: acf() got an unexpected keyword argument 'unbiased '

**Comment by nils-braun** [comment]
Hi @XudongWang97!
Thanks for sharing those details. The respective file was changes approximately 2 years ago to not contain the "unbiased" parameter anymore, so I am confused why this shows up in version 0.20.1 (3 months ago) again. Are you sure you are using this version and not maybe an older one (just want to double check). How did you install tsfresh? Via pip or conda?

**Comment by XudongWang97** [comment]
Thank you @nils-braun 
I install tsfresh by pip. Now I create a new py3.9 environment and it works. It's strange that I cannot reproduce the error in the old py3.7 one. Some dependency issue?

**Comment by nils-braun** [comment]
Hm yes - if you have some time you could run a pip freeze in both environments and see if there is some significant diff?

**Comment by nils-braun** [comment]
Thanks for looking into this. If you have some time, could you check the package versions in both environments (e.g. with pip freeze) and see if there are significant differences? Thank you!

**Comment by kiraminnie** [comment]
Hi @nils-braun , thank you for your support. I have installed the 0.18.0 version. Do you think this is the problem? I don't understand the right combination of versions for Python, tsfresh, statsmodels. It seems there is a combination of libraries working...

Thank you again for your support.

**Comment by nils-braun** [comment]
Yes, tsfresh 0.18.0 is from 2021 (!), so it definitely will not work with any recent packages. I would recommend updating to the newest version (0.20.2). In general, the newest version of a package is usually the best one. If all package authors have their dependencies declared correctly, you do not need to sort out a combination yourself and pip will do it for you.

**Comment by kiraminnie** [comment]
Thank @nils-braun, I think the problem is that I'm unable to upgrade tsfresh.

I installed many times, all the times using a new environment but the version is always the same: 0.18.0

(WGM_tsfresh) andrea@pcdyn-sl-143 ~ % pip install --upgrade tsfresh  
Requirement already satisfied: tsfresh in ./opt/anaconda3/envs/WGM_tsfresh/lib/python3.12/site-packages (0.20.2)
Requirement already satisfied: requests>=2.9.1 in ./opt/anaconda3/envs/WGM_tsfresh/lib/python3.12/site-packages (from tsfresh) (2.31.0)
Requirement already satisfied: numpy>=1.15.1 in ./opt/anaconda3/envs/WGM_tsfresh/lib/python3.12/site-packages (from tsfresh) (1.26.4)
Requirement already satisfied: pandas>=0.25.0 in ./opt/anaconda3/envs/WGM_tsfresh/lib/python3.12/site-packages (from tsfresh) (2.2.1)
Requirement already satisfied: scipy>=1.2.0 in ./opt/anaconda3/envs/WGM_tsfresh/lib/python3.12/site-packages (from tsfresh) (1.13.0)
Requirement already satisfied: statsmodels>=0.13 in ./opt/anaconda3/envs/WGM_tsfresh/lib/python3.12/site-packages (from tsfresh) (0.14.1)
Requirement already satisfied: patsy>=0.4.1 in ./opt/anaconda3/envs/WGM_tsfresh/lib/python3.12/site-packages (from tsfresh) (0.5.6)
Requirement already satisfied: scikit-learn>=0.22.0 in ./opt/anaconda3/envs/WGM_tsfresh/lib/python3.12/site-packages (from tsfresh) (1.4.2)
Requirement already satisfied: tqdm>=4.10.0 in ./opt/anaconda3/envs/WGM_tsfresh/lib/python3.12/site-packages (from tsfresh) (4.66.2)
Requirement already satisfied: stumpy>=1.7.2 in ./opt/anaconda3/envs/WGM_tsfresh/lib/python3.12/site-packages (from tsfresh) (1.12.0)
Requirement already satisfied: cloudpickle in ./opt/anaconda3/envs/WGM_tsfresh/lib/python3.12/site-packages (from tsfresh) (3.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in ./opt/anaconda3/envs/WGM_tsfresh/lib/python3.12/site-packages (from pandas>=0.25.0->tsfresh) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./opt/anaconda3/envs/WGM_tsfresh/lib/python3.12/site-packages (from pandas>=0.25.0->tsfresh) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in ./opt/anaconda3/envs/WGM_tsfresh/lib/python3.12/site-packages (from pandas>=0.25.0->tsfresh) (2024.1)
Requirement already satisfied: six in ./opt/anaconda3/envs/WGM_tsfresh/lib/python3.12/site-packages (from patsy>=0.4.1->tsfresh) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in ./opt/anaconda3/envs/WGM_tsfresh/lib/python3.12/site-packages (from requests>=2.9.1->tsfresh) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in ./opt/anaconda3/envs/WGM_tsfresh/lib/python3.12/site-packages (from requests>=2.9.1->tsfresh) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./opt/anaconda3/envs/WGM_tsfresh/lib/python3.12/site-packages (from requests>=2.9.1->tsfresh) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in ./opt/anaconda3/envs/WGM_tsfresh/lib/python3.12/site-packages (from requests>=2.9.1->tsfresh) (2024.2.2)
Requirement already satisfied: joblib>=1.2.0 in ./opt/anaconda3/envs/WGM_tsfresh/lib/python3.12/site-packages (from scikit-learn>=0.22.0->tsfresh) (1.4.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./opt/anaconda3/envs/WGM_tsfresh/lib/python3.12/site-packages (from scikit-learn>=0.22.0->tsfresh) (3.4.0)
Requirement already satisfied: packaging>=21.3 in ./opt/anaconda3/envs/WGM_tsfresh/lib/python3.12/site-packages (from statsmodels>=0.13->tsfresh) (24.0)
Requirement already satisfied: numba>=0.55.2 in ./opt/anaconda3/envs/WGM_tsfresh/lib/python3.12/site-packages (from stumpy>=1.7.2->tsfresh) (0.59.1)
Requirement already satisfied: llvmlite<0.43,>=0.42.0dev0 in ./opt/anaconda3/envs/WGM_tsfresh/lib/python3.12/site-packages (from numba>=0.55.2->stumpy>=1.7.2->tsfresh) (0.42.0)
(WGM_tsfresh) andrea@pcdyn-sl-143 ~ % conda search tsfresh           
Loading channels: done
# Name                       Version           Build  Channel             
tsfresh                       0.18.0    pyhd3eb1b0_0  pkgs/main

**Comment by kiraminnie** [comment]
Hi @nils-braun I've reinstalled Anaconda and now I was able to install the right version of tsfresh, which is working. Thank you very much for your help
