### ISSUE TITLE
Shapelet extraction

### ISSUE THREAD

**Issue by GillesVandewiele** [blue-yonder/tsfresh#111]
One interesting feature with an explanatory ability is [shapelet extraction](http://alumni.cs.ucr.edu/~lexiangy/Shapelet/kdd2009shapelet.pdf).

Would maybe be interesting to implement within this package? A far from optimal code example by me can be found [here](https://www.kaggle.com/group16/leaf-classification/shapelets)

**Comment by MaxBenChrist** [comment]
Looks interesting. Have you seen the part of our documentation that describes how to implement your own feature calculator?

**Comment by MaxBenChrist** [comment]
I don't have time to read the paper at the moment. But, from a short glimpse on the paper I am not sure if this is a good fit for tsfresh. Essentially the paper describes a classifier not a feature extraction algorithm. It uses subsequences to do a nearest neighbor search, a k nearest neighbor search. 

If we deploy this, suddenly tsfresh gets a state. This could be fine for the sklearn transformers but is not a good fit for our convenience functions extract_features and extract_relevant_features

**Comment by GillesVandewiele** [comment]
It tries to extract subseries of timeseries that are most discriminative for a certain class. So it takes as input a set of time series with corresponding labels and returns shapelets that can be used as features for a classifier.

**Comment by MaxBenChrist** [comment]
We have the convention that features must be real valued numbers. If I get you right, those shapelets are subsequences of the original time series?

**Comment by GillesVandewiele** [comment]
For k classes, you could have a 'best' shapelet for each class and then the distances to each of these classes could be added (k features), or the index of the closest shapelet could be added (1 feature). 

The difference maybe is that here, a whole dataset is required to extract the 'best' shapelets instead of just 1 time serie.

**Comment by MaxBenChrist** [comment]
By this you get a feature calculator with a state. Essentially you have to train the calculator (to get the shapelets) and then predict with it ( to get the distance to the class).

This means that tsfresh would have need to have separated data sets for train / test set. Up until now, the users can extract features for their whole data and do the train/test split by themselves.

Don't get me wrong, I don't say that the shapelet feature is not helpful, but If we implement it, we would have to change our API (the `extract_feature` method would be replaced by a `fit` and `transform` )

**Comment by MaxBenChrist** [comment]
We already have sklearn based transformers, so we could start with that.

**Comment by jneuff** [comment]
I haven't looked at the paper yet. tsfresh being stateless has many advantages, but sooner or later we might have to introduce state to support features like this one. We should start thinking about ways to do this. As @MaxBenChrist said, our sklearn-transformers are probably a good starting point.

**Comment by MaxBenChrist** [comment]
the biggest drawback will be that our APIs become more complicated. Eventually it lead to removing `extracting_features` and `extracting_relevant_features` and instead only offering the transformers.

**Comment by earthgecko** [comment]
@GillesVandewiele I have watched this one closely, that shapelet extraction looks very interesting, even it if is not totally suited to the stateless of tsfresh, it is very interesting in terms of the specific timeseries domain, thanks for pointing it out.  It will be interesting to see if is can be hooked into tsfresh via the sklearn-transformers as just another feature, however I would say it is an interesting feature, so as they say, where there is a will the is a way :)

But I would agree, that do not make the tsfresh APIs more complicated, extension it often preferable to modification in many instances.  I studied Botany and when I originally saw this when you posted it and looked at the Kaggle and Eamonn Keogh endorsed paper and I actually wondered to myself...

Could every single timeseries be closest matched to a KNOWN leaf profile, there being a lot of leaves...  Is there a data source for ALL KNOWN leaf profiles - images, other?

If there was... every leaf could be converted to a "timeseries", the features for every leaf profile could then be calculated with tsfresh.  Then you could compare timeseries on the score of the leaf profiles and compared to the score of the timeseries (perhaps with some scale equality).  But you could possibly compare timeseries to known leaves.  Timeseries similarity comparisons.  However, you can possibly do that simply with tsfresh alone, without shapelet extraction.

However, I think adding some known, natural, evolutionary baselines would be **super cool** :D

**Comment by MaxBenChrist** [comment]
We had some discussion about the statelessness before. Personally, I would love to have something like k-Nearest-Neighbour with dynamic time warping as an additional feature calculator.

But, one thing we should not forget is that having a state also means that the parallelisation of tsfresh becomes way, way harder to implement, you would have to parallelize every single feature having a state. 

If we had more contributors, we could tackle this.  But, at the moment, tsfresh already takes way too long for big data sets. We should focus on getting it faster and getting the parallelization right.

**Comment by earthgecko** [comment]
Me too but http://www.cs.ucr.edu/~eamonn/meaningless.pdf still applies to k-Nearest-Neighbour I think... I honestly cannot totally remember, all I know is that timeseries are difficult.  Timeseries with machine learning are difficult.

I would assert, possibly until tsfresh came along.  A small step for...

**Comment by earthgecko** [comment]
@MaxBenChrist ^^ as I inferred, I forgot :)

**Comment by earthgecko** [comment]
@MaxBenChrist I reckon it can be hacked, if it was desirable (optional) in a manner that does not change tsfresh's stateless-ness.  I reckon tsfresh just made "one small step for...." timeseries and machine learning, imho.

I think that right now the stateless-ness of tsfresh should remain stateless for now.  However it is not beyond the realms of possibilities that tsfresh-plugins could not work and do ```g, f, d``` with tsfresh.

I would personally like to see the possibilities that the tsfresh in its current stateless-ness stale can do, however I too can see a number of possibilities, in terms of the opportunities tsfresh possibly presents.

These are clever people :)  @GillesVandewiele you did a Kaggle, I reckon you could probably do a plugin :)

**Comment by GillesVandewiele** [comment]
> Could every single timeseries be closest matched to a KNOWN leaf profile, there being a lot of leaves... Is there a data source for ALL KNOWN leaf profiles - images, other?

The cool thing about shapelets is that they learn this leaf profile. They search for a subserie in the timeserie that best distinguishes one certain leaf class from all other classes.

> These are clever people :) @GillesVandewiele you did a Kaggle, I reckon you could probably do a plugin :)

I could indeed help with the implementation, but I could use some help as well. First off, my code is far from very clean (I never really written clean code in my life before). Moreover, many possible optimization techniques could be implemented to decrease the computational complexity, which is required when the dataset becomes large.

**Comment by earthgecko** [comment]
@GillesVandewiele well I will definitely be having a play around with Shapelet extraction myself whether around tsfresh or standalone, but probably not until next year now, so until then :)

**Comment by GillesVandewiele** [comment]
You can definitely start from my kaggle code base for this, many possible optimizations are left (pruning techniques). Would be nice to see an evaluation on the leaf classification dataset? How much could you increase your predictive performance by incorporating shapelet features? Something I would like to investigate, but it is yet impossible given the computational complexity of my current code base...

**Comment by MaxBenChrist** [comment]
At the moment we have some other, internal challenges to face, see #119. 

As soon as we solved them, we will discuss the possibility of stateful feature calculators. Shapelets seem like a good choice for a future feature calculotrs.

**Comment by ClimbsRocks** [comment]
Would love to see some shapelets in here eventually! But I'm happy to see the team able to make prioritization decisions and maintain focus- that bodes well for the health of this project long-term.

**Comment by GillesVandewiele** [comment]
Hey everyone,

Just to give everyone a heads-up. I've started implementing different algorithms to discover shapelets in timeseries. 

https://github.com/GillesVandewiele/pyShapelets

**Comment by Ezekiel-Kruglick** [comment]
Just to jump in here.... I've long been a fan of the output of Keogh's group, but I don't see how to implement shapelets in the format of tsfresh now because it would cause a huge explosion in number of features and most would be useless. Having said that, one could imagine a pre-processing step doing shapelet discovery (K-NN using various distance metrics and sub-segments) which would generate a smaller number of features that we could then extract as part of the main extracting_features paradigm. Those features could be passed in as a parameter combination fed to a feature calculator that would look a lot like the ones already present. I'd be willing to help with that if we find a high level architectural vision we like.

**Comment by MaxBenChrist** [comment]
> Just to jump in here.... I've long been a fan of the output of Keogh's group, but I don't see how to implement shapelets in the format of tsfresh - as I think multiple people have expressed above.

Me too. Dynamic time warping with kNN often achieves amazing accuracies in time series classification tasks. I have not used shapelet approaches so far. 

>  Having said that, one could imagine a pre-processing step doing shapelet discovery (K-NN using various distance metrics and sub-segments) which would generate a smaller number of features that we could then extract as part of the main extracting_features paradigm. Those features could be passed in as a parameter combination fed to a feature calculator that would look a lot like the ones already present. I'd be willing to help with that if we find a high level architectural vision we like.

This sounds very interesting. I like the idea of splitting to finding of the shapelets and then extraction of features. In such a way it will not brake our paradigm that the value of one feature does not depend on the other features.

Actually, I have been quietly working on *tspreprocess*, a package to preprocess the time series, e.g. denoising, compressing etc. It is not yet open source. We could add the finding of the shapelets to that package.

However, at the moment, I am not sure about the following things:

- How to find the shapelets.
- If a kNN is the right way to find the shapelets: How to parallelize the kNN search and implement it in an efficient way*
- How can we serialize the shapelets such that we can use them in a tsfresh feature calculator?

* it took me forever to find an efficient python DTW + kNN implementation.

@Ezekiel-Kruglick are you familiar with the literature on shapelets?

**Comment by Ezekiel-Kruglick** [comment]
@MaxBenChrist @GillesVandewiele 

I found this talk be Keogh in which he spends about half the time talking about shapelets: https://www.youtube.com/watch?v=sD-vvN_st58&t

He notes that shapelets are a special form of unsupervised motif discovery once you've turned the shape into a psuedo time-series.

I have used a variety of Motif discovery algorithms. I think this gives us a potential skeleton though:

def method_involving_motifs(x, params):

[params contains, for example, a number N of combinations equal to the number of top most important motifs you want to use and the scenario (motif counts, best match location...)]

1. Run motif discovery to return N motifs (possibly store them somewhere for the user???)

2) for each parameter and motif combination:
    Generate feature by counting motif matches, finding motif score for the chosen scenario (e.g. count of matches...)

This would fit with our current extractor architecture, doesn't require preprocessing, and uses our standard conventions for combination handling.

Is there a recommended way to pass out the motif details?

This would likely get the param for compute intensive, but at least it avoids kNN (as it *should* since this isn't unsupervised - although we will be generating best motif detection not best motifs for predicting cases). If we want to do best prediction we need to have access to the classifications at feature extraction...

**Comment by Ezekiel-Kruglick** [comment]
@MaxBenChrist   - I almost missed your last question. I have used DTW and kNNs a lot and done Motifs of which shapelets are a special case, but so far my specific exposure to "shapelets" have been only through reading papers from Keogh's group. I do have a collection of about 300MB of material from Keogh's group from back a few years when they were handing out data and code.

**Comment by ClimbsRocks** [comment]
tspreprocess sounds like a great idea! doesn't clutter up the main package with unnecessary complexity, but gives quite a few advanced tools to the power users who seek them out. 

@MaxBenChrist : out of curiosity, which "efficient python DTW + kNN implementation" did you end up going with? I'm facing that same struggle.

**Comment by MaxBenChrist** [comment]
> @MaxBenChrist : out of curiosity, which "efficient python DTW + kNN implementation" did you end up going with? I'm facing that same struggle.

I use kNN from sklearn with a small wrapper and an implementation of DTW in C

**Comment by MaxBenChrist** [comment]
> I found this talk be Keogh in which he spends about half the time (second half) talking about shapelets: https://www.youtube.com/watch?v=sD-vvN_st58&t

Interesting talk. 

> I do have a collection of about 300MB of material from Keogh's group from back a few years when they were handing out data and code.

what kind of code? maybe some blazing fast C implementations? :D

@Ezekiel-Kruglick I agree with what everything you said. do you want to develop a small proof of concept (does not yet to be 100% in tsfresh format) and then we iterate from that on?

**Comment by Ezekiel-Kruglick** [comment]
@MaxBenChrist  Yes, sure, I'll work up a motif discovery and feature extractor algorithm.

**Comment by Ezekiel-Kruglick** [comment]
Update: I have a working motif extractor. That brought up other higher level issues when I applied it to data like removing duplicates and how to extract counts. I'm working on those higher level issues and building support options now like filtering based on having at least M occurrences over the time series to keep from finding less-useful highly matching pairs.

**Comment by Ezekiel-Kruglick** [comment]
FYI: I had to code up algorithm myself as the other motif extractors I found using python all had issues that would have prevented us from using for features or had special cases that were okay for those authors but not good enough for a general tool. Currently it's pretty slow.

**Comment by Ezekiel-Kruglick** [comment]
@MaxBenChrist  I've sped up the code a bunch and have some tools around the main functionality. I don't see a dev branch, what is your preferred approach for large amounts of beta-level code? Probably ready to upload in a day or two.

**Comment by nils-braun** [comment]
Just do a fork and create a pull request - we will handle the rest! Looking forward to your PR :-)

**Comment by GillesVandewiele** [comment]
Hey guys, sorry for my inactivity. I was on holiday!

I think extracting features from the shapelets itselves will not be that useful, since the shapelets are already small subseries and the minimal distance from a timeserie to different extracted shapelets are already quite discriminative features.

I like your motif extraction @Ezekiel-Kruglick ! Do the motifs/subsequences need to occur multiple times EXACTLY in the timeserie or is the shape enough? Will investigate the code more thoroughly in the nearby future for sure!

If I'm right (correct me otherwise), the motif extraction differs from the shapelet extraction since it only operates using 1 timeserie at a time (just look at patterns that occur multiple times in the same timeserie), while the shapelet extraction requires all (or a subset) of timeseries to calculate information gain etc on?

**Comment by Ezekiel-Kruglick** [comment]
@GillesVandewiele 
"Do the motifs/subsequences need to occur multiple times EXACTLY in the timeserie or is the shape enough?" - Right now I'm using euclidean distance and the user can put in a distance cutoff of their preference when generating features. So the match need not be exact (exact would be distance zero), and is adjustable to whatever the user wants. The distance metric computation is also an accessible property of the motif extractor so it can be replaced by a user function if desired.

"the motif extraction differs from the shapelet extraction since it only operates using 1 timeserie at a time (just look at patterns that occur multiple times in the same timeserie), while the shapelet extraction requires all (or a subset) of timeseries to calculate information gain etc on" - It depends on how you look at it :)  The shapelets paper is looking at all of the data at once. Keogh in talks describes shapelets as motifs but with input series based on shape descriptors so we can modify as we like.

This actually brings up an interesting point. @MaxBenChrist et al: do the feature extractors get passed chunked data for a single id at a time? I'm getting much better results applying it to the whole data series all at once first so that I can find motifs that are in multiple IDs. Is there a way to get the whole data column first to generate motifs? Then we would use those motifs for each id to do feature extraction.

**Comment by MaxBenChrist** [comment]
@GillesVandewiele 

You can quote other people by appending a ">" to the beginning of the sentence, see https://help.github.com/articles/about-writing-and-formatting-on-github/

> This actually brings up an interesting point. @MaxBenChrist et al: do the feature extractors get passed chunked data for a single id at a time? I'm getting much better results applying it to the whole data series all at once first so that I can find motifs that are in multiple IDs. Is there a way to get the whole data column first to generate motifs? Then we would use those motifs for each id to do feature extraction.

I think you are mixing up the finding of the motifs with the calculation of the motif features. The calculation of the feature is done inside *tsfresh*, with every time series independently. So we have fixed motifs and calculate the feature for every time series. But, the finding of the motifs can be done in any fashion, even on whole data set at once. I would add it to another package, maybe *tspreprocess*.

> Is there a way to get the whole data column first to generate motifs?

I am not sure about that question? you could just extract the `value` column from the time series container

**Comment by Ezekiel-Kruglick** [comment]
@MaxBenChrist - Sorry for using imprecise wording, I meant the way you said it. "Finding" the features in the whole stream meant "picking out data that makes for good features". I think we mean the same thing.

>I am not sure about that question? you could just extract the value column from the time series container.

Is there a best practice for that? I notice it can be passed in many forms and I'm not 100% certain my interpretation of where it gets stored as I'm still learning the codebase.

Sorry for delays, some work got in the way

**Comment by MaxBenChrist** [comment]
No worries. We can later easily convert every tsfresh data format to the format that you picked. I feel that the flat data frame from https://tsfresh.readthedocs.io/en/latest/text/data_formats.html would be best fitting for this task.

**Comment by Ezekiel-Kruglick** [comment]
@MaxBenChrist  I've put some work so far at this branch: https://github.com/Ezekiel-Kruglick/tsfresh/tree/motif_discovery

You'll see new code in the feature_extractors directory (motifs.py) and a set of tests for it. I can use that within an ipython notebook to do motif extraction and feature generation and have done so to test usefulness and default settings. Can you take a look at the bottom of feature_calculators.py and tell me what you would put in there to access that flat data frame? Following the data I don't see how it would get to there or how to pass it as a parameter.

**Comment by MaxBenChrist** [comment]
@Ezekiel-Kruglick 

> You'll see new code in the feature_extractors directory (motifs.py) and a set of tests for it. I can use that within an ipython notebook to do motif extraction and feature generation and have done so to test usefulness and default settings. Can you take a look at the bottom of feature_calculators.py and tell me what you would put in there to access that flat data frame? Following the data I don't see how it would get to there or how to pass it as a parameter.


The feature calculators only have access to a singular time series. So your motif eplorer `motif_explorer` can only access one singular time series. I would not put the explorer into the `tsfresh/feature_extraction/feature_calculators.py` but in another separate module.

**Comment by MaxBenChrist** [comment]
The notebook with the example is not checked in, is it? @Ezekiel-Kruglick 

I would like to try it. Also let me know once the `tsfresh/feature_extraction/motifs.py` is ready for a first review.

**Comment by Ezekiel-Kruglick** [comment]
@MaxBenChrist 
> The feature calculators only have access to a singular time series.
Okay, that's what I thought earlier, I guess we talked past each other a bit. Since there is a preprocessor being discussed but we don't have an implementation yet would it be appropriate for me to put in function primitives for now that can be called manually for now? Then we can compose them into auto-extractors as we figure out the preprocessor format?

> The notebook with the example is not checked in, is it?
My apologies, I'm testing on proprietary data for work so I can't check that in. I can make and check in a notebook once we resolve the above so I know what the API should look like for now.

**Comment by Ezekiel-Kruglick** [comment]
@MaxBenChrist 
Okay, there is now an example notebook over on my fork. In theory this fork is ready for a pull request as it shouldn't break anything, but it also won't start running by itself as the only thing that calls the motif functions is the example notebook. This would put the motif code and example notebook in the repository so that you can play around with it in your preprocessor. If you think that's a good idea say so and I'll issue the pull request.

I definitely think motif finding should be something the user has to at least select with a parameter as on long datasets it can be very slow.

 I can separately think about other features using motifs, right now my only executed example motif feature is counting how many times a given motif is in a strip of data. It might be fun to go through Keoghs papers and see what other metrics we can use once motifs are available.

**Comment by MaxBenChrist** [comment]
@Ezekiel-Kruglick sorry for the delay.

Great work already.

There are a few things that I would change. .e.g 

- save the found motifs as `fc_settings`. this allows the addition of found motifs to an existing `kind_to_fc_parameters` settings object
- move the motif detection in another submodule

I think the best way to work on that would be to open a pr and then iteratively go over the code there. I want to code on this as well so maybe we should not target the master but a branch "motif" with that pr. 

> I can separately think about other features using motifs, right now my only executed example motif feature is counting how many times a given motif is in a strip of data. It might be fun to go through Keoghs papers and see what other features we can generate once motifs are available.

Agree, once we have a motif detection, we can think of many feature calculators

**Comment by Ezekiel-Kruglick** [comment]
Sounds like a good plan. Can you please create the core motif branch? Bitbucket would allow me to issues a pull request to new branch but it appears GitHub does not have that.

Zeke

**Comment by MaxBenChrist** [comment]
@GillesVandewiele I created the motif branch. 👍

**Comment by GillesVandewiele** [comment]
Great! Let me know if I can help! Also, if you ever plan on going for shapelets, I'll gladly integrate my code...

**Comment by MaxBenChrist** [comment]
> Great! Let me know if I can help! Also, if you ever plan on going for shapelets, I'll gladly integrate my code...

Sounds good. 

Just to be on the same page: Shapelets are a special kind of Motif. They are those motifs that have the highest discriminative power in a classification task, right?

**Comment by GillesVandewiele** [comment]
> Just to be on the same page: Shapelets are a special kind of Motif. They are those motifs that have the highest discriminative power in a classification task, right?

Yes, they are somewhat similar. Motifs are subseries that occur multiple times, shapelets are subseries that are very discriminant for time series of a specific class (they will probably occur in most timeseries of that class). 

The main difference is that in order to extract shapelets, you must have the whole dataset. This is no requirement for motif extraction.

**Comment by MaxBenChrist** [comment]
Thanks for the explanation. 

This sounds more like a direct classifier? Or can you build features from the shapelets?

**Comment by GillesVandewiele** [comment]
You store the shapelets in some kind of dictionary, and for each timeserie you measure the minimal distance to each of the shapelets in your dictionary.

You thus form a feature vector of length K, where K is the number of shapelets in your dictionary. Another option is to take the argmin of this vector to reduce the number of features. 

Moreover, you can use these shapelets to transform your data: [paper](https://ueaeprints.uea.ac.uk/40201/1/LinesKDD2012.pdf)

**Comment by MaxBenChrist** [comment]
> You store the shapelets in some kind of dictionary, and for each timeserie you measure the minimal distance to each of the shapelets in your dictionary.

This sounds very similar to motifs. So, if I get it right: The difference lays not in calculating the features but in finding the shapelet (best discriminative power of singular occurrence of subsequence) or motif (most often occurring subsequence). Later when you call the feature calculator, it does the same: for a given subsequence (either motif or shapelet), it searches for occurrences/distance to the pattern in the given time series. Am I right?

**Comment by GillesVandewiele** [comment]
@MaxBenChrist that's correct!

**Comment by MaxBenChrist** [comment]
I finally managed to spend a few hours to work on the motif branch. 

@Ezekiel-Kruglick 

when looking for motifs, you go over the sequence and then select the current subsequence as motif pattern. But then you do not look backwards for the occurrence of that pattern. 

See https://github.com/blue-yonder/tsfresh/blob/0dd40edb36e127aece70d664eabcbd3dc001471d/tsfresh/feature_extraction/motifs.py#L160

Is that intended?

Also, I have some questions, I added them as TODO lines.

**Comment by Ezekiel-Kruglick** [comment]
@MaxBenChrist  - Yes, looking only forwards for the pattern is intended otherwise you get doubles of all the matches. A match between two segments A, B will be symmetric such that the distance metric is the same comparing A--> B and B -->A. If you compare backwards then for every close matching segment pair you'll get both pairs. Similarly there is no need to compare a test segment X against any previous segments because X has already been compared to every segment when that segment looked forward and X was in the forward section. Thus removing backward looking during matching eliminates double occurrences and saves time without losing any information.

I did not think of that at first, I had to think about it and realize it when I was looking at all the double pairs of motifs.

I will go look at the TODO lines.

**Comment by Ezekiel-Kruglick** [comment]
@MaxBenChrist - I think this is all the questions that weren't addressed above. Let me know when you aren't playing with the code anymore and I can make changes as needed before any merge if you like.

# TODO: can we somehow remove the dependence on `as_strided`? even its own docstrings warns not to use it...
    return np.lib.stride_tricks.as_strided(data, shape=dimensions, strides=steplen)

Hah, yes, sorry.  I suppose I've been using that trick for years. There are many ways to generate a sliding window and any of them will work. Preferable to do it in numpy for speed. I can fix once things are stable from other work you are doing if you like.

# todo: the lists should not be constructed from scratch in every iteration, maybe work with append?
An excellent point, and I see how to do it no problem

# todo: why the factor 8? why not 7 or 6
    if motif_length * 8 > len(data):
Keogh mentioned it in passing in one of his talks so I tossed that constant in. We could make it an over_rideable parameter with a default value perhaps? Whatever you like

# todo: wouldn't 2 * motif_length be enough?
    for start in range(len(data) - (3 * motif_length)):

I was finding 2*motif_length got off-by-one in certain cases (wound up with one too few data to compare). Now that I look at it though I may have fixed that two different ways so that might actually work now. I would want to write some tests for the special cases before saying for sure but that might be changeable.

**Comment by MaxBenChrist** [comment]
@Ezekiel-Kruglick 

thank you for the detailed answers.

> Let me know when you aren't playing with the code anymore and I can make changes as needed before any merge if you like.

From now own, I will also work with pull requests towards this branch. I will not push commits to the `motif` branch directly anymore. As only we two are working on that branch at the moment, I think it is fine to use those TODOs to organize ourselves. I see no need to open issues.

> I would want to write some tests for the special cases before saying for sure but that might be changeable.

Yes, we should make sure that we test everything properly 

Regarding the `as_strided`, I think it returns a view so it could consume less memory for long time series than a constructed array. But as said, its docstring frightened me a little bit :D

**Comment by Ezekiel-Kruglick** [comment]
@MaxBenChrist 
Sounds like a good plan. I'll grab a new branch tonight or Monday and work on it.

**Comment by MaxBenChrist** [comment]
@Ezekiel-Kruglick 

I worked on the motif branch again. I have a good feeling about the current state. I think we can start to polish the docstrings. 

One think that is missing is a normalization beforehand, right? I have read somewhere that you should  z-transform your time series before looking for motifs.

**Comment by Ezekiel-Kruglick** [comment]
@MaxBenChrist 
Looking good, I will work from the new one when I add more (spoiler: work just got very busy). As an update I did take a look at the _generate_candidates line with "for start in range(len(data) - 3 * motif_length):" and I am now able to replicate the corner case where "2 * motif_length" doesn't work but it's a deep issue and I'm still working on understanding it.

I think normalization is probably desired as a default. There can be some special cases where the scale is known to be an important signal so perhaps we can allow that to be turned off? In any case a simple sklearn.preprocessing.normalize is likely all we'd need unless you see something more complicated?

I defer to your opinion on where to put it :)

**Comment by MaxBenChrist** [comment]
> Looking good, I will work from the new one when I add more (spoiler: work just got very busy). As an update I did take a look at the _generate_candidates line with "for start in range(len(data) - 3 * motif_length):" and I am now able to replicate the corner case where "2 * motif_length" doesn't work but it's a deep issue and I'm still working on understanding it

Perfect

> I think normalization is probably desired as a default. There can be some special cases where the scale is known to be an important signal so perhaps we can allow that to be turned off? In any case a simple sklearn.preprocessing.normalize is likely all we'd need unless you see something more complicated?

The normalizing itself is not a problem. But I have not figured out where to normalize. Lets say that you have three time series `a, b, c`. Now, you concatenate them, normalize them and then look for motifs:

```
x=[a, b, c]
x = normalize(x)
m = find_motifs(x)
```

Now, later you look for those motifs inside the individual time series `a, b, c`, so you will have to normalize them, but you do that individually, so

```
a = normalize(a)
n = count_motif(a, m)
```

You know, the normalization on `x` and on `a` will behave differently. Worst case, even if the motifs stem from `a`, you will not find them in `a` later. 

Is that topic touched in one of the papers?

**Comment by Ezekiel-Kruglick** [comment]
@MaxBenChrist 
To some degree normalization is one of reasons and tradeoff drivers for SAX, so there is a lot of discussion about how and when to do it across the work from Keogh's lab. 

I *think* we have to normalize on each time series a,b,c so that the concatenation of [a, b, c] is the concatenation of normalized time series events. 

That would certainly make sense for the scenarios I've been thinking of and my planned usage. Inverting the question, can we think of any cases where that would mess things up?

**Comment by MaxBenChrist** [comment]
> @MaxBenChrist
To some degree normalization is one of reasons and tradeoff drivers for SAX, so there is a lot of discussion about how and when to do it across the work from Keogh's lab.
> I think we have to normalize on each time series a,b,c so that the concatenation of [a, b, c] is the concatenation of normalized time series events.
> That would certainly make sense for the scenarios I've been thinking of and my planned usage. Inverting the question, can we think of any cases where that would mess things up?

I spent some time thinking about this. I think, we should not only normalize each time series individually but also forbid motifs that span over the array border. 

Here an example with non normalized time series
```
a = [1, 2]
b=[0, 1, 0, 0]
x = a + b # x = [1, 2, 0, 1, 0, 0]
```
in this case, `[2, 0, 1]` is not a valid motif.

I am sure we can implement that quite easily.

**Comment by Ezekiel-Kruglick** [comment]
@MaxBenChrist 
Yes, forbidding motifs from spanning the border is necessary. Can you think of a fast way to do it? I was thinking in the motif generator we could test for the index being within a motif length of the end but testing is nontrivial considering that different samples may have different lengths.

**Comment by Ezekiel-Kruglick** [comment]
@MaxBenChrist 
Okay, I have found a reference in a tutorial by Keogh et al that says, "Essentially all datasets must have every subsequence z-normalized." (They then mention "There are a handful of occasions where it does not make sense to z-normalize, but in those cases, similarity search does not make sense either.")

So I would say the plan to normalize each time series agrees with best practices.

**Comment by MaxBenChrist** [comment]
> So I would say the plan to normalize each time series agrees with best practices.

Alright. The normalization will be quite easy to add.

> Yes, forbidding motifs from spanning the border is necessary. Can you think of a fast way to do it? I was thinking in the motif generator we could test for the index being within a motif length of the end but testing is nontrivial considering that different samples may have different lengths.

I started sketching a possible way to realize this. You can find it on the multimotifs branch. However, I did not test or even tried to use it yet. Time is limited, as always :-/

In my solution, I am assuming that the data comes in as a list of time series. I flatten this list but save where the borders are. Then i use the existing methods with the flat data sequence. 

What do you think?

**Comment by Ezekiel-Kruglick** [comment]
@MaxBenChrist 
Sorry for long absence, main job got in the way. I cloned and was looking at working on this, which branch should I work from? I see ongoing work in multmotifs that looks quite significant, is that where I should work?

**Comment by MaxBenChrist** [comment]
> Sorry for long absence, main job got in the way. I cloned and was looking at working on this, which branch should I work from? I see ongoing work in multmotifs that looks quite significant, is that where I should work?

Nice to hear from you again. :D yes, on the multimotif branch I added a mechanism (based on the `good_start` array) that prevents motifs from spawning over borders. The `good_start` list contains all indices where an motif can start without spawning over the borders.

At the moment it only works for subsequences of the same lenght, but we can easily extend that to different sized sequences.

**Comment by Ezekiel-Kruglick** [comment]
I think I have resolved the remaining todos.  I am having trouble with your added good_start portion, though. The reason it breaks tests are that it expects the data to be in the form of a series of lists (assuming I have that right)? We pass data in as a single long list with sample IDs in another column, is it internally turned into a series of lists when passed to the feature generators? I didn't know that and will need to make some changes if that is the case.

**Comment by MaxBenChrist** [comment]
> We pass data in as a single long list with sample IDs in another column, is it internally turned into a series of lists when passed to the feature generators? I didn't know that and will need to make some changes if that is the case.

Inside tsfresh, we use actually operate on chunks, which are a triple of id, kind, and the time series. So the long column of with the time series data is split into sub series.

Sooo, it would be beneficial if we also operate on such sub series. However, it is not mandatory to operate on such data structures, we can also operate on a singular time series with another series saving the id.

**Comment by Ezekiel-Kruglick** [comment]
okay, look like I need to go learn more about that. Is each chunk guaranteed to be a single id and kind and the whole of that single id and kind? So it's a single "sample" or "experiment", one might say?

**Comment by MaxBenChrist** [comment]
> okay, looks like I need to go learn more about that. Is each chunk guaranteed to be a single id and kind and the whole of that single id and kind? So it's a single "sample" or "experiment", one might say?

yes, exactly.

**Comment by Ezekiel-Kruglick** [comment]
@MaxBenChrist  
I think perhaps we're talking past each other. Didn't we discuss and agree that the initial motif finding would be on *the whole data stream* instead of chunks specifically because finding motifs shared by different samples is far more interesting than motifs constrained within a single sample? *Then* we need to pass those motifs into the main feature finding system that breaks things up into chunks and does multiprocessing, at which point we are dealing with chunks and generating chunk-specific features determined by the motifs. Right?

But the good_start portion in the multimotifs branch assumes things are already chunked. So perhaps in the pre-processing module you've been working on (that I don't think I've seen) is there an intermediate stage where the passed in data is a data structure containing all of a particular type of chunks? Is that in the branch I have? If you point me at where you want to call the motif-finding that would be very useful.

**Comment by MaxBenChrist** [comment]
Ah, I see your point. 

I think we should have a Hangout Session and discuss this in person. I would like to explain a few things, writing everything down would take quite some time.

Are you free sometime next week? My mail address that I use for hangout is max.christ@me.com

**Comment by nils-braun** [comment]
Was there any news on this? If yes, please reopen. If not, we leave it closed.
