### ISSUE TITLE
Impute takes quite some time

### ISSUE THREAD

**Issue by nils-braun** [blue-yonder/tsfresh#123]
If we want to be faster, we probably also have to make sure the "impute" function is not that slow...

**Comment by MaxBenChrist** [comment]
Good point!

**Comment by F-A** [comment]
Hi all,

I think one of the problem is tha youare iterating through the columns of the dataframe. When you have a lot of ime series and extract a lot of features you get a huge number of columns and this iteration takes a lot of time...

For example, using the tsfresh.utilities.dataframe_functions.get_range_values_per_column function on a dataframe with 200 columns and 60 indeces I get an execution time for this function of 329ms (best of 3 execution on a total of 100 with %timeit).

I wrote an alternative function working on the numpy array directly:
```
 def get_range_values_per_column(df):
    """
    Retrieves the finite max, min and mean values per column in df and stores them in three dictionaries, each mapping
    from column name to value. If a column does not contain finite value, 0 is stored instead.
    :param df: Dataframe
    :return: Dictionaries mapping column names to max, min, mean values
    """
    column = df.get_values()
    masked = np.ma.masked_invalid(column)
    
    columns = df.columns
    
    col_to_max     = dict( zip(columns, np.max(masked,axis=0) ) )
    col_to_min     = dict( zip(columns, np.min(masked,axis=0) ) )
    col_to_median  = dict( zip(columns, np.median(masked,axis=0) ) )
        
        
    return col_to_max, col_to_min, col_to_median
```

It get an execution time of 25ms (same measure). This function still needs to be more tested (it still gets a problem with median in some cases) and maybe improved but this could give the right direction for improving the performance.

For the record, I found this out, because I wanted to detect features on 60 EEG channels. The feature extraction was still usable but the impute function took way to long so I stopped it...

**Comment by jneuff** [comment]
Nice investigation! Are you planning to cover all cases with your function? Can you open a pull request with your proposal?

**Comment by F-A** [comment]
To be honest I'm not sure how much time I can spend on this... I just planned to try out tsfresh to classify EEG trials but the impute function was to slow for me, so I looked at the function and just wanted to document my investigation. 
I'm currently looking at the impute function, to see if one can do something similar.
Depending on how far I come, and if my function make through the unit tests I'll try to do a PR.

**Comment by MaxBenChrist** [comment]
@F-A have you tried to install the latest master version? It will impute early on, after each feature is calculated. That should speed up the calculation further.

**Comment by MaxBenChrist** [comment]
> This function still needs to be more tested (it still gets a problem with median in some cases)

What kind of errors?

**Comment by MaxBenChrist** [comment]
I like your implementation of `def get_range_values_per_column(df):` very much. We should switch ours with yours

**Comment by F-A** [comment]
I also reimplemented impute. They now both pass the unit tests. I'll do the
PR tomorrow.
It now rum far faster. I'll give more details tomorrow when I'm back in the
office.

**Comment by MaxBenChrist** [comment]
Awesome. Looking forward to  your pr :)
