### ISSUE TITLE
Provide a stand alone script operating on csv

### ISSUE THREAD

**Issue by jneuff** [blue-yonder/tsfresh#13]
We could provide a stand alone script that runs tsfresh directly on csv files and returns the results as another csv file.

**Comment by earthgecko** [comment]
Possible for sure :) It could probably do json too...

Makes me think of a lite version of TPOT - https://github.com/rhiever/tpot

Nice project :)

**Comment by nils-braun** [comment]
@jneuff The question is only, how should the user give options to the script. I mean e.g. the column names can easily by set by console arguments, but setting the feature extraction/selection settings are a bit inconvenient (because of their wide range of options). I would prefer to use the default settings in this case only and only export the settings on which columns to use.

**Comment by MaxBenChrist** [comment]
We already have a script, see scripts/run_tsfresh.py.

What are indeed missing are some parameters for the column names and so on
