### ISSUE TITLE
Bug: Calculation of Fourier coefficients is not independent from other Fourier coefficients

### ISSUE THREAD

**Issue by MaxBenChrist** [blue-yonder/tsfresh#228]
I was working on unit tests for the `fft_coefficient` feature calculator, when I stumbled about the following bug:

``` Python

i = np.linspace(-1, 1, num=100)
x = np.sin(i*np.pi)

for max_lag in range(1, 10):
    ...:     print(np.fft.rfft(x, max_lag).real)
# will print
[ -1.22464680e-16]
[-0.06342392  0.06342392]
[-0.19001637  0.09500819]
[-0.37926762  0.12659245  0.12608271]
[-0.6304156   0.15831485  0.15689295]
[-0.94244905  0.19039278  0.18734766  0.18696817]
[-1.31411151  0.22311752  0.21741968  0.21651855]
[-1.74390642  0.25685141  0.24710692  0.24544456  0.24510063]
[-2.23010315  0.29202479  0.27642732  0.27368103  0.27291845]
```

So what is happening here? The value of a fft coefficient depends on the maxlag that is used to calculate the fft.

The bad line is here: https://github.com/blue-yonder/tsfresh/blob/master/tsfresh/feature_extraction/feature_calculators.py#L742

Why is this bad? 

This means that the value of e.g. the Fourier coefficient for coefficient==3 depends on the configuration for the other features. This breaks our convention that the value of a feature only depends on his configuration

How can we fix this? I see multiple solutions

- make the `fft_coefficient` a "simple" function calculator instead of "combine" (this is computational expensive because it will calculate one fft for EVERY coefficient..)
- add an additional parameter `maxlag` (not user friendly)
- use length of individual time series as maxlag (will Also increase the computational complexity)

I tend to include the maxlag parameter as I do not want to increase the runtime, speed is everything ;)

It would be very helpful to have somebody with a background in signal processing to comment on this. I had a lecture on Fourier transformations but that was 5 years ago, so my knowledge is limited

**Comment by nikhaas** [comment]
I give my 2cents to this issue, although I am not an expert in signal processing. Tbh, my following conclusions are drawn from ~1h of research on Fast Fourier Transformation (FFT). Please correct me if I am mistaken.

I suspect you might have a misconception about how FFT works. This is supported by the naming of your variable `max_lag`. This tastes like you inspect some kind of lag operator to be involved in the calculation, alike the computation of the autocorrelation. This is not the case. The FFT is only an efficient algorithm to calculate the Discrete Fourier Transform. I liked [this post](https://dsp.stackexchange.com/questions/509/what-effect-does-a-delay-in-the-time-domain-have-in-the-frequency-domain), it is stated there

> The discrete Fourier transform (DFT), commonly implemented by the fast Fourier transform (FFT), maps a finite-length sequence of discrete time-domain samples into an **equal-length sequence** of frequency-domain samples. The samples in the frequency domain are in general complex numbers; they represent coefficients that can be used in a weighted sum of complex exponential functions in the time domain to reconstruct the original time-domain signal.

The naming of the function `fft_coefficient` indicates that you are somehow interested in retrieving some of these coefficients and use them as features. As stated in the quote, for a sequence `x` it is true that `len(x) ==  len(fft(x))`. 
Your parameter `max_lag` corresponds to the parameter `n` in [`numpy.fft.rfft`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.fft.rfft.html#numpy.fft.rfft), where it is said 
> n : int, optional
Number of points along transformation axis in the input to use. If n is smaller than the length of the input, the input is cropped. If it is larger, the input is padded with zeros. If n is not given, the length of the input along the axis specified by axis is used.

So with your `max_lag`, you in fact input the sequence `x[:max_lag]` to the `fft` function. Of course, the results of `fft(x, 1)` and `fft(x, 2)` differ, because they operate on different sequences. Btw, in your example, 
```python
np.fft.rfft(x, 1).real  # val: -1.22464680e-16
x[0]  # val: -1.2246467991473532e-16
```
So the fft of only one value is the value itself.
What you might have expected by altering the parameter `max_lag` (i.e. the parameter `n`) is to get a "fit" of less FFT-coefficients than the length of the sequence, what is not how Discrete Fourier Transformation works. But this is only a guess. 

My suggestion:
- Do not pass a parameter to the `fft` method. This in fact truncates the input.
- Speed should not be an issue, because the complexity of the FFT algorithm is `O(n log(n))`, whereas DFT is normally `O(n**2)`. And, as a characteristic of the FFT for a real-valued series, [the second half of coefficients are simply complex-conjugates of the first half](https://en.wikipedia.org/wiki/Discrete_Fourier_transform#The_real-input_DFT), which can be and is exploited
- Proposed selection procedure for the coefficients: 
    - Take the real parts or absolute values (magnitudes) of the first `max_lag` coefficients or
    - calculate the angle of each complex number and take the first `max_lag` angles or
    - sort the coefficients by real part / absolute value (magnitude) / angle and take the first `max_lag` ones
![Imaginary numbers in the coordinate system](https://upload.wikimedia.org/wikipedia/commons/7/7a/Complex_number_illustration_modarg.svg)
*r is the magnitude / absolute value of the imaginary number, \phi the associated angle. Use Pythagoras to calculate it.*

**Comment by MaxBenChrist** [comment]
Thanks for contributing @nikhaas.

First, the equation of the DFT for the following discussion is 

![60627d7b56cbf58e87ccb5c3ee92a36ebccc62f5](https://user-images.githubusercontent.com/13162426/28055522-8f40ac20-6619-11e7-9f70-852dfd61470f.png)

So, the individual features that we calculate with `fft_coefficient` are the A_k 


> I suspect you might have a misconception about how FFT works. This is supported by the naming of your variable max_lag. This tastes like you expect some kind of lag operator to be involved in the calculation, alike the computation of the autocorrelation. This is not the case. The FFT is only an efficient algorithm to calculate the Discrete Fourier Transform. I liked this post, it is stated there

The reason why we did not call this parameter `n` as in the equation above and instead used `max_lag` was that in an old version the `n` was used for the number of samples / time series length. So, a clash of parameter names made us to use `max_lag`.

But you are right. We are actually truncating the time series, which is bad...


> Take the real parts or absolute values (magnitudes) of the first max_lag coefficients

We are already returning the real part

> Speed should not be an issue, because the complexity of the FFT algorithm is O(n log(n)) (see introduction of the Wikipedia article), whereas DFT is normally O(n**2). And, as a characteristic of the FFT for a real-valued series, the second half of coefficients are simply complex-conjugates of the first half, which can be and is indeed exploited

Speed is always an issue, especially with time series. Just saying it is O(n log n) so it will be fines is not good. We have to benchmark the changes. 
Also regarding the second part with the complex-conjugates: This is the reason why we use `numpy.fft.rfft` and not `numpy.fft.fft` ;).

> calculate the angle of each complex number and take the first max_lag angles or

I do not get why you want to return the angle? every dft coefficient corresponds to a certain frequency. What does the angle corresponds to?

> sort the coefficients by real part / absolute value (magnitude) / angle and take the first max_lag ones

I am not really sure what you are proposing here. Every feature calculator should return a coefficient with a fixed index

**Comment by MaxBenChrist** [comment]
So, TL:DR

-Ditch `max_lag` operator. 
- Use the length of the time series instead.

This means that we get basically the A_k from k=0 to the length of the time series "for free". I am not sure how to adapt the settings.

**Comment by MaxBenChrist** [comment]
See the PR. Indeed the runtime is okayish, 

``` Python
import numpy as np
import pandas as pd
import matplotlib.pylab as plt
import time

lengths = [10, 50, 100, 200, 300, 400, 500, 600, 700, 1000, 2000, 3000, 4000, 5000, 10000]
t = [0]*len(lengths)

n_iter = 10000

for _ in range(n_iter):
    i=0
    for l in lengths:
        x = np.random.normal(size=l)
        start_time = time.time()
        np.fft.rfft(x)
        t[i] += (time.time() - start_time)
        i+=1
        
plt.plot(lengths, t, label="normal")
plt.xlabel("Individual time series length")
plt.ylabel("Total runtime in seconds for 10000 time series")
plt.show()


```

![Uploading Unknown.png…]()


So, for a dataset of 10,000 time series, each of length 10,000, the extraction of all dft takes around 2s.
