### ISSUE TITLE
Test ipython notebooks for python3

### ISSUE THREAD

**Issue by MaxBenChrist** [blue-yonder/tsfresh#247]
I had to turn off the testing of python notebooks for py3. 

It would be good to also check the notebooks unter python3

**Comment by nikhaas** [comment]
Why did you need to turn off the py3 testing? This might be related to my experience.

My [PR for a new notebook produced an error](https://github.com/blue-yonder/tsfresh/pull/243). This is because I use Anaconda with it's notebook extensions - I can choose an Anaconda Kernel among the "normal" python2 and python3 kernels. This information is stored in the metadata which is located at the bottom of the notebook. [Link to travis error log](https://travis-ci.org/blue-yonder/tsfresh/jobs/254186231#L984)

This is an example notebook metadata spec from [robot_failure_example.ipynb](https://raw.githubusercontent.com/blue-yonder/tsfresh/master/notebooks/robot_failure_example.ipynb):
```json
"metadata": {
  "kernelspec": {
   "display_name": "Python 2",
   "language": "python",
   "name": "python2"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.11"
  }
 }
```
A local execution of the test suite yielded no success either. No notebook passed the test. This might be because my "Standard" Python2 environment (I am on Linux) does not have all the requirements, but `nbconvert` seems to use this environment.

It would be nice if one could specify which kernel to use for notebook execution via `nbconvert` during testing.

You might want to overwrite the metadataspecification in the Jupyter Notebook. This can be done temporarily by a flag. You can modify [test_notebooks.py](https://github.com/blue-yonder/tsfresh/blob/master/tests/test_notebooks.py) with the `"--ExecutePreprocessor.kernel_name=python"` flag:

```python
def _notebook_run(path):
    """
    Execute a singular ipython notebook at path and returns the cells and outputs

    :returns (parsed nb object, execution errors)
    """

    dirname, _ = os.path.split(path)

    with tempfile.NamedTemporaryFile(suffix=".ipynb") as fout:
        args = ["jupyter", "nbconvert",
                "--to", "notebook", "--execute",
                "--ExecutePreprocessor.timeout=600",
                "--ExecutePreprocessor.kernel_name=python",  ##!! New !!
                "--output", fout.name, path
                ]
        print(" ".join(args))
        subprocess.check_call(args)

        fout.seek(0)
        nb = nbformat.read(fout, nbformat.current_nbformat)

    errors = [output for cell in nb.cells if "outputs" in cell
              for output in cell["outputs"] \
              if output.output_type == "error"]
    return nb, errors
```

[Link to nbconvert docs with kernel traitlet](http://nbconvert.readthedocs.io/en/latest/execute_api.html#execution-arguments-traitlets). It might also be possible to say `python2`, `python3` and `''` (default), where the last argument might be equivalent to specifying `python`? [See the GitHub Jupyter nbconvert issue](https://github.com/jupyter/nbconvert/pull/177)

After that, [the Travis test of inspect_dft_features passed](https://travis-ci.org/blue-yonder/tsfresh/jobs/254220836#L516).

It might be a good idea to overwrite this metadata with a notebook push to the main repo. I don't know if this is possible, but this way, everyone who pulls the notebook gets a "clean" KernelSpec with no user-/contributor specific kernel information that is present when you use Anaconda.

The non-automated workaround: Specify the notebookkernel to Python 2 before push. But I'd prefer the automated solution.

**Comment by MaxBenChrist** [comment]
We are committing notebooks checked it, so people can read them on the github repo. 

indeed, that creates problem with python3 + meta kernel on py2. this is why I turned off the testing for py2.

So. I am not fully getting why you propose here. is the 

```
"--ExecutePreprocessor.kernel_name=python"
```

solving the issue? we could have a switch that uses `"--ExecutePreprocessor.kernel_name=python2"` and `"--ExecutePreprocessor.kernel_name=python3"`.

**Comment by nikhaas** [comment]
I'll have a look at it soon. I'll try to get the notebook tests running locally.

**Comment by MaxBenChrist** [comment]
I added a switch on the py3nbtest branch

**Comment by MaxBenChrist** [comment]
See https://github.com/blue-yonder/tsfresh/blob/py3nbtests/tests/test_notebooks.py#L27

**Comment by MaxBenChrist** [comment]
I am not sure if the code in our notebooks is ready for py3 though
