### ISSUE TITLE
Expected 2D array, got 1D array instead:

### ISSUE THREAD

**Issue by suryareddy9593** [blue-yonder/tsfresh#461]
# Decision Tree Regression
 
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
 
# Importing the dataset
dataset = pd.read_csv('Position_Salaries.csv')
X = dataset.iloc[:, 1:2].values
y = dataset.iloc[:, 2].values
 
# Fitting Decision Tree Regression to the dataset
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X, y)
 
# Predicting a new result
y_pred = regressor.predict([8.3])
 
# Visualising the Decision Tree Regression results (higher resolution)
X_grid = np.arange(min(X), max(X), 0.01)
X_grid = X_grid.reshape((len(X_grid), 1))
plt.scatter(X, y, color = 'red')
plt.plot(X_grid, regressor.predict(X_grid), color = 'blue')
plt.title('Decision Tree Regression')
plt.xlabel('Position level')
plt.ylabel('Salary')
plt.show()

Error: 
ValueError: Expected 2D array, got 1D array instead:
array=[ 8.30000019].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample. 

How to resolve this error to obtain ? I'm using canopy Python 3.5.2.

**Comment by delyanr** [comment]
Just to illustrate the problem better, let's presume you were predicting using two values - instead of `regressor.predict([8.3])` you wanted `regressor.predict([8.3, 8.3])`. The regressor cannot know whether this 1D array represents TWO features of ONE sample, or TWO samples with ONE feature each. The regressor requires you to be specific, i.e. `regressor.predict([[8.3], [8.3]])` tells it that this now 2D array represents TWO samples with ONE feature each. In your case, even though this is not an issues since you have only one value, the regressor still requires you to use 2D array, i.e. `regressor.predict([[8.3]])`.

**Comment by MaxBenChrist** [comment]
Also, this is an question for scikit learn. They changed the classifier / regressor API such that those corner cases where its not clear if you have one sample (and m features) or one feature (and m samples). This is not the right bug tracker for such question(but I am sure you can find a bunch of similar questions on stackoverflow)
