### ISSUE TITLE
Possibility to extract features by rolling windows from time series?

### ISSUE THREAD

**Issue by michael-ziedalski** [blue-yonder/tsfresh#506]
I am using `tsfresh=0.11.2`. I am working with a long univariate time series, and, reading up on `tsfresh`, especially the [forecasting docs](https://tsfresh.readthedocs.io/en/latest/text/forecasting.html), it seems like it would be perfect for calculating features on a rolling window basis. Basically, to set a `window=10` argument (for example), so for the the first 10 time-indexed points, `t=0:10`, have the selected features, like mean, be calculated based on them and output that value. For the next value, calculate the same features based on points `t=1:11`, and so on and so forth for the rest of the time series.

I tried following the above guide for my data below, but I get none-sense answers. 

```
from tsfresh import extract_features
from tsfresh.utilities.dataframe_functions import roll_time_series

from tsfresh.feature_extraction import MinimalFCParameters
settings = MinimalFCParameters()

rolled_mini_timeseries = roll_time_series(mini_test, column_id='id', column_kind='acoustic_data', column_sort='time', rolling_direction=10)

extracted_features_test_piece = extract_features(rolled_mini_timeseries, default_fc_parameters=settings,column_id='id', column_value='acoustic_data', column_sort='time', disable_progressbar=False, n_jobs=4)
```

My data:
<img width="186" alt="screen shot 2019-03-03 at 4 39 06 pm" src="https://user-images.githubusercontent.com/43689829/53702308-8e853880-3dd3-11e9-86a3-be592ed9e8d1.png">

**Comment by nils-braun** [comment]
Did you have a look into our documentation on the data format here https://tsfresh.readthedocs.io/en/latest/text/data_formats.html?

Because you are passing the value "acoustic_data" as the kind column. This means tsfresh thinks for every distinct value of acoustic_data (which is -2, 0, 2 and 4) you have a different kind of think (could be sensor direction or whatever). I guess however acoustic_data is your value of the sensor and you only have one kind of sensor.
So just replace `column_kind="acoustic_data"` with `column_kind=None` in the call to `roll_time_series` and it works as expected.

**Comment by michael-ziedalski** [comment]
Thank you! Even though some time has passed, I finally understand now how to get the feature extraction to work, thank you. I did indeed go over the docs multiple times, but its instructions were never felt clear to me.
