### ISSUE TITLE
Forecasting X values ahead

### ISSUE THREAD

**Issue by rhagan09** [blue-yonder/tsfresh#573]
Hi, 

I was wondering if it is possible to use the tsfresh forecasting method to predict, for example, 4 values ahead in time. I have followed the https://github.com/blue-yonder/tsfresh/blob/master/notebooks/timeseries_forecasting_google_stock.ipynb example provided and am getting some great results for prediction of next value in time series.

I have a time series that has occurrences every 15 minutes and would be looking to predict an hour in advance. Is this possible?

Many Thanks.

**Comment by anderl80** [comment]
It's possible to do this recursively. Predict 1 step ahead, then use this prediction for the next forecast step again. I'm wondering if this is easily done with tsfresh methods, too.

**Comment by rhagan09** [comment]
So are you creating new dataframes when for each iteration or how are you implementing this recursively? Thanks!

**Comment by nils-braun** [comment]
Great question. Let me just assume you have a value x(t) that you want to predict (for nomenclature). I see two possibilities:
* you can either use the idea if what @anderl80 described and train your model to predict one step in time x(t) -> x(t + 1). However, you would need to have a model that not only predicts your x, but also all the features to then feed them back to your model. I think this will be pretty hard.
* or you just train your model to predict not x(t + 1), but x(t + 4). There is no technical reason that prevents you from doing this. This might not be possible from your domain problem, but this is something different :-)

So you follow the notebook until the point when the model is trained. Instead of feeding y (which is basically just `x["high"][1:]`) you just give it `x["high"][3:]`.
This all the trick.

Feel free to reopen if you have any more technical problems.

**Comment by rhagan09** [comment]
Hi, 

Thanks very much for your help. 
Just a question, where you say 'instead of feeding y', where exactly in the code do you mean?:
    ada.fit(X.iloc[:i], y[:i])
    y_pred[i] = ada.predict(X.iloc[i, :].values.reshape((1, -1)))[0]
I.e. where should the x["high"][3:] go?

Rachael.

**Comment by nils-braun** [comment]
At the fitting step, so where the .fit() is called (you can also generate your own y = x["high"][3:] so you can just reuse this code).

**Comment by rhagan09** [comment]
@nils-braun this is what I have tried but for some reason it doesn't like the "high" giving:
`KeyError: 'high'`
Is there something I am missing?

Many thanks for your help.

**Comment by nils-braun** [comment]
Sorry, the "high" was special to the notebook. In general if the data you want to forecast is named `forecast` you just use `forecast[3:]`.

Maybe you post a bit of your code so we are talking about the same variables :-)

**Comment by rhagan09** [comment]
@nils-braun Ok, so my data is held in x, which has a time column (every 15 mins) and volume column (measured variable). 
Therefore, if I am correct I should have `y = x["volume"][3:]` ?
Then I have this (following from example):

```
`#ADA BOOST REGRESSION
ada = AdaBoostRegressor(n_estimators=10)
yada_pred = [np.NaN] * len(y)

isp = 4  # index of where to start the predictions
assert isp > 0

for i in tqdm(range(isp, len(y))):
    y = x["Volume"][4:]
    ada4.fit(X.iloc[:i], y[:i])
    yada_pred4[i] = ada4.predict(X.iloc[i, :].values.reshape((1, -1)))[0]
    
yada_pred4 = pd.Series(data=yada_pred4, index=y.index)`


```

Would this then give me predictions an hour ahead?
Should I have yada_pred4[i+4] instead so that its filling in the prediction 4 steps ahead, or how does it know to predict an hour ahead?

**Comment by rhagan09** [comment]
@nils-braun so at time x(t) i want to predict the volume at time x(t+4)

**Comment by nils-braun** [comment]
Basically correct (assuming you want to predict the volume). I would just move the
`y = x["Volume"][4:]` to the top before everything.

And the "4:" basically means it tries to predict the value 4 times in the future (t + 4).

I will close this issue now again as it seems you have figured it out :-)

**Comment by emangy** [comment]
Hi @rhagan09 , 

Can you please, explain how you managed to perform forecasting for 1 point in the future. The way the features is extracted requires the y values, which does not exist for the future time series ?
