### ISSUE TITLE
extract_relevant_features in celery tasks

### ISSUE THREAD

**Issue by flamby** [blue-yonder/tsfresh#603]
Hi,

When running `extract_relevant_features` inside a celery task, I get an error: `daemonic processes are not allowed to have children`.

So I followed recommandation of [this issue](https://github.com/blue-yonder/tsfresh/issues/458) by passing `n_jobs=0`. It's a little better as the function is running but eventually is killed like so: 
```
lib/python3.7/site-packages/billiard/pool.py", line 1267, in mark_as_worker_lost
    human_status(exitcode)),
billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL).
```

Is it planned to support celery? Perhaps by using [billiard](https://github.com/celery/billiard) instead of the `multiprocessing` module, or even better by using [dask](https://github.com/dask/dask).

Thanks!

**Comment by dbarbier** [comment]
Hi, it is not hard to test such a support, define your own class derived from DistributorBaseClass in `tsfresh/utilities/distribution.py`; you may have to modify some routines to add a distributor argument, as is done in `extract_features`.

But if your job crashes, this is surely because it ran out-of-memory, you should first have something working before trying to distribute it.  I suggest to try with different values of `default_fc_parameters` (try `EfficientFCParameters()` or `MinimalFCParameters()`), with `n_jobs` still set to 0.

**Comment by flamby** [comment]
Hi @dbarbier 

> Hi, it is not hard to test such a support, define your own class derived from DistributorBaseClass in `tsfresh/utilities/distribution.py`; you may have to modify some routines to add a distributor argument, as is done in `extract_features`.

Thanks.

> But if your job crashes, this is surely because it ran out-of-memory, you should first have something working before trying to distribute it. I suggest to try with different values of `default_fc_parameters` (try `EfficientFCParameters()` or `MinimalFCParameters()`), with `n_jobs` still set to 0.

You pointed me in the right direction. Despite the function works without celery, I completly forgot that a while ago I had to limit task memory using the celery `--max-memory-per-child` argument.
So it was indeed due to memory constraint at the celery level.

Thanks!
