### ISSUE TITLE
Out of Memmory while Feature Extraction

### ISSUE THREAD

**Issue by Infatum** [blue-yonder/tsfresh#614]
I've faced Memory Overflow with 376Gb Ram on the Google Cloud Computation Engine, while doing Feature Extraction on the 2 years of Time-Series Data Bitcoin prices. After the progress bar showed 100% it continued to eat memory, which resulted in Memory Overflow! Please, fix this behaviour, otherwise I will write about this issue on Towards Data Science
![image](https://user-images.githubusercontent.com/6483272/69904239-eb3a7180-13ac-11ea-9dac-d5d2af724984.png)

**Comment by nils-braun** [comment]
> Please, fix this behaviour, otherwise I will write about this issue on Towards Data Science

Sorry, what?
I think I have totally misunderstood this sentence. I actually hope I did.

tsfresh is open source software. It is free to use, it even comes with MIT licence (which is rather open I would say). Everyone is open to contribute to the software and fix problems.

"Threatening" the developers by telling them, "please fix this, otherwise I will write bad things about you" - that is not how community works. 

We are happy to accept pull requests, reported problems, proposals, anything which tries to help the community and bring the project forward. 

No one here is paid for doing this, we all do this in our spare time. You get a product from the community, built by the community, supported by the community - for free.

I am super happy to discuss your problem with you. And everyone will try to fix the problem for the sake of the software.

And not because you threaten us to write about it on Towards Data Science.
