### ISSUE TITLE
Feature explainability FFT  -- Feature request

### ISSUE THREAD

**Issue by wolfdr** [blue-yonder/tsfresh#639]
Perhaps I did not see it in the docs or the code, but I was looking for an explanation of the Fast Fourier coefficient... how many Hertz does it relate to? So that relates to the sampling. But what is the sampling? (There is no actual sampling passed into the np.fft I saw... then I gave up) Could not really find that out. Is there any way to add to the docs how to calculate it...? Or ideally add to the variable name.

Disclaimer: I did not use FFT in years so I might be missing the obvious here. Apologies if this is the case.

**Comment by nils-braun** [comment]
Maybe I am not 100% about your question, but we (well, we just pass on to numpys fft function, so basically numpy) do not sample the time series but we use whatever we get as an input.
Maybe you are a bit confused by thinking of the continous FFT, because what we do is a discrete FFT (https://en.wikipedia.org/wiki/Discrete_Fourier_transform)
If you are interested in the frequency values, you might want to check out https://docs.scipy.org/doc/numpy/reference/generated/numpy.fft.fftfreq.html#numpy.fft.fftfreq.

Just one note: tsfresh has no notation of units (such as time or frequency). It just uses what it gets. Other domains might not even hav a "time series" but a series depending on some other variable (so it would not be Hz, but maybe 1/m or something). As a default, we just use the first 100 output of the rfft function.

We did not add any description on how the FFT is calculated because - honestly - there is so much documentation out there. If the links did not help you, I am happy to provide more information!

And if you have a concret idea on how to improve the docu - we are super happy!

**Comment by wolfdr** [comment]
Yes I found this out now.  My problem with the doc is that when you read it in a first go you read:

Does tsfresh support different sampling rates in the time series? Yes! 
Does tsfresh support different time series lengths? Yes!

and you read only on a closer look that this only applies for different time series types... yet each of the types need to have the same length and the same constant sampling rate.

I think what the doc needs is a very concrete mention in capitals and red that 
- each time series needs to have equidistant time steps and that the time coordinate it is not used (you say that only in one place kind of hidden). That the data is in a coordinate form (t, value) indicates that the interpolation of coordinates onto a regular grid is somehow taken care of by tsfresh.
- each time series needs to have equal lengths.

I think what is also missing is suggestions on how to deal with time series that are not equal length and not on a constant sampling rate:
- sampling rate: I guess that is really non trivial... I did not spent a lot of time on time series but bringing (x,y,value) to a regular grid is really not that trivial. I have some ideas about this. But perhaps you have better ideas..

- unequal length: I think here different things need to be done for different transformers... Anything average related or quantile related I would keep the length different / unchanged. However, for FFT you kind of need to pad to the same length, otherwise the coefficient means something completely different in every row. So basically I would guess one needs to runs tsfresh twice and carefully select the some transformers from the padded run and some other transformers from the unpadded run.

With regard to the padding part, I think that should be fairly easy to implement from the tsfresh side, so that could be seen as a feature request. For some of the transformers which need it, pad sequence to equal length (e.g. there must be a standard way to pad data for a fft so that the coefficients are not too distorted)...

... and with regards to fft, if you know the total time and the number of points / sampling rate, then you also know the frequency so somehow you'd need to let people know what the length of the padded series is to that they can work it out...


I am not a time series expect so perhaps none of that makes sense.
