### ISSUE TITLE
Feature request: RelevantFeatureAugmenter kind_to_fc_parameters to accept params loaded from json

### ISSUE THREAD

**Issue by amundvedal** [blue-yonder/tsfresh#643]
1. OS: `macOS 10.13.6`
2. version `1.14.1`
3. dataset `load_robot_execution_failures` 
4. A minimal code snippet which reproduces the problem/bug

```
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from tsfresh.examples import load_robot_execution_failures
from tsfresh.transformers import RelevantFeatureAugmenter

pipeline = Pipeline([('augmenter', RelevantFeatureAugmenter(column_id='id', column_sort='time')),
            ('classifier', RandomForestClassifier())])

df_ts, y = load_robot_execution_failures()
X = pd.DataFrame(index=y.index)

pipeline.set_params(augmenter__timeseries_container=df_ts)
pipeline.fit(X, y)


kind_to_fc_parameters = tsfresh.feature_extraction.settings.from_columns(pipeline[0].transform(X))


with open('kind_to_fc_parameters_comprehensive.json', 'w', encoding='utf-8') as f:
        json.dump(kind_to_fc_parameters, f, ensure_ascii=False, indent=4)


pipeline = Pipeline([('augmenter', RelevantFeatureAugmenter(column_id='id', column_sort='time', kind_to_fc_parameters=pd.read_json('kind_to_fc_parameters_comprehensive.json').to_dict())),
            ('classifier', RandomForestClassifier())])

df_ts, y = load_robot_execution_failures()
X = pd.DataFrame(index=y.index)

pipeline.set_params(augmenter__timeseries_container=df_ts)
pipeline.fit(X, y)
```

5. Any reported errors or traceback
ValueError: at least one array or dtype is required

The problem seems to be that `tsfresh.feature_extraction.settings.from_columns` returns a `dict` containing `ndarray` type. Would be great to be able to both save and load params to json without worrying about this.

**Comment by nils-braun** [comment]
Interestingly enough I did not get the same error message that you did - but another one. Anyways, here are some thoughts:
* I would not use `pd.from_json` but rather just do a (normal) `json.load(f)`. That did solve the first problem for me.
* The next problem is with the cwt function - there is a small bug which only gets triggered in your use case. I will fix it soon. With that, the script runs through.

Not related: is there a reason you use another RelevantFeatureAugmenter also in the second part (where you only want to do the feature extraction, because you did the selection already)?

**Comment by amundvedal** [comment]
@nils-braun the only reason the `RelevantFeatureAugmenter` is in both places is that I quickly copy-pasted the lines to make the example. :P Thanks for noting it :)

**Comment by nils-braun** [comment]
With the current master your script should run now (with the changes I proposed)

**Comment by nils-braun** [comment]
If not, please re-open :-)
