### ISSUE TITLE
Using Benjamini Hochberg for multiclass classification

### ISSUE THREAD

**Issue by wahidelchaar** [blue-yonder/tsfresh#683]
Hello, I am currently doing a multiclass classification problem, and thinking about using the Benjamini Hochberg procedure in the `extract_relevant_features()` module. But I saw in the documentation that the module expects y to be binary if it's a classification problem. Would the Benjamini Hochberg still apply in my case? If not, what other methods do you suggest?

**Comment by kempa-liehr** [comment]
Hi, this is an interesting question, which we had come across in several different project. This would be a suitable approach:
1. Extract the time-series features using extract_features (without any selection)
2. For every class label: Fit individual instances of the FeatureSelection transformer for the one-vs-all classification
3. Concatentate the p_value attribute for the fitted FeatureSelection transform 
4. Use this vector of p-values with statsmodels.stats.multitest.multipletests in order to find statistically significant features.
5. Due to the repeated one-vs-all testing, features might appear several times in this list. Depending on your problem, you need to decide how often a feature needs to be selected in order to be used for your classification problem.

**Comment by kempa-liehr** [comment]
@wahidelchaar, the multiclass classification problem is discussed on pages 8-9 of the following paper:  https://rdcu.be/b6BXC
