### ISSUE TITLE
Deal with complex numbers

### ISSUE THREAD

**Issue by CristianTuretta** [blue-yonder/tsfresh#711]
Hi,
I'm using *tsfresh* on a dataset which contains complex numbers, they came from Fast Fourier transformation. When I try to extract features from this kind of dataset an error occurs and it says:
`NotImplementedError: function is not implemented for this dtype: [how->mean,dtype->complex128]` .

My code is similar to the example you wrote on example notebooks.
What should I do in order to avoid this error?

The snipper of code which causes this error is:
`extraction_settings = ComprehensiveFCParameters()`
`X_fft_tsfresh = extract_features(df_fft, column_id='id', column_sort='time',
                                 default_fc_parameters=extraction_settings,
                                 impute_function=impute)`

My operating system is MacOS 10.15.5 

The version of *tsfresh* that I'm using is 0.16.0

**Comment by nils-braun** [comment]
Hi @CristianTuretta!

Thanks for the issue. The problem is, as written in the error message, that most (if not all) of our feature calculators are not implemented to cope with complex numbers, but only with real numbers.

I would do the following: convert your single column of complex numbers into two (or four) derived columns of real numbers: the real and the imaginary part and maybe also add the abs and the phase as third and forth column. Then try tsfresh on all of these columns.
I know that you will loose a lot of information as the columns are then treated independently, but I guess that especially if your data comes from a fft, the abs and phase alone will already contain some useful information.

**Comment by CristianTuretta** [comment]
Thank you @nils-braun I appreciate your response.
