### ISSUE TITLE
Strategy for missing values

### ISSUE THREAD

**Issue by cbows** [blue-yonder/tsfresh#756]
Hi, 

in the [FAQ](https://tsfresh.readthedocs.io/en/latest/text/faq.html) I read that tsfresh supports feature extraction on time series with different sampling rates if the data is provided as a [stacked DataFrame](https://tsfresh.readthedocs.io/en/latest/text/data_formats.html#input-option-2-stacked-dataframe-or-long-dataframe). Since I need this for my project, I played around with this a little bit and find the results quite odd, but maybe I am misunderstanding something. Here is what I did:

I created some sample data containing two kinds of time series `x` and `y`, where `y` is just a sub-sampled version of `x`, containing only the first and last value
```python
data = {
    "id": [1, 1, 1, 1, 2, 2, 2],
    "time": [0, 1, 2, 3, 0, 1, 2],
    "x": [9, 9, 9, 7, 1, 1, 2],
    "y": [9, np.nan, np.nan, 7, 1, np.nan, 2]
}
```
Then, I create the stacked DataFrame
```python
timeseries = (
    pd.DataFrame(data)
    .melt(id_vars=["id", "time"], value_vars=["x", "y"], var_name="kind")
    .dropna()
)
```
Finally, I extract features with tsfresh
```python
features = extract_features(
    timeseries,
    column_id="id",
    column_kind="kind",
    column_sort="time",
    column_value="value",
    default_fc_parameters=settings.MinimalFCParameters(),
    disable_progressbar=True,
    n_jobs=0,
)
```
This gives the following results
```
   x__sum_values  x__median   x__mean  x__length  x__standard_deviation  x__variance  x__maximum  ...  y__median  y__mean  y__length  y__standard_deviation  y__variance  y__maximum  y__minimum
1           34.0        9.0  8.500000        4.0               0.866025     0.750000         9.0  ...        8.0      8.0        2.0                    1.0         1.00         9.0         7.0
2            4.0        1.0  1.333333        3.0               0.471405     0.222222         2.0  ...        1.5      1.5        2.0                    0.5         0.25         2.0         1.0
```

There are a couple of things that I find unintuitive here:
* The length of `x` and `y` is always different, although `y` was sampled at `t_start` and `t_end`, which is why I'd expect a length same as `x` (in terms *actual* length).
```
   x__length  y__length
1        4.0        2.0
2        3.0        2.0
```
* The rest of the features are calculated as if the `np.nan` values never existed, e.g.
```
    x__mean  y__mean
1  8.500000      8.0
2  1.333333      1.5
```
where `y__mean` is 1.5 only if you assume linear interpolation of missing values. For other features, like `sum_values` they are simply ignored
```
   x__sum_values  y__sum_values
1           34.0           16.0
2            4.0            3.0
```

I can think of two scenarios:
1. This is intended behaviour and I should impute missing values myself before passing them to tsfresh.
    * In this case I have two issues:
        - The relevant entry in the FAQ seems kind of misleading, and should be clarified
        - This is quite memory-inefficient for large time series with different sampling rates. Instead of filling missing values beforehand, this could be pushed down to the feature extraction by setting an interpolation strategy that will determine how features are calculated. For example, there would be more efficient ways to calculate the mean if you know that missing values will be filled by repeating previous values (`interpolation_strategy='constant'`) or linearly interpolated (`interpolation_strategy='linear'`).
2. This is not intended behaviour.
    * Well, then it is a bug.

### System information

`lsb_release -ds`: Ubuntu 18.04.5 LTS
`python --version`: 3.7.8
`tsfresh.__version__`: 0.17.0

**Comment by nils-braun** [comment]
Hi @cbows !
Thank you very much for your issue and the great MWE (and sorry it took a while to answer it).

Let me try to clarify some things, which might cause the confusion first before going into your specific questions. As always, we are very happy to improve our documentation (which definitely needs improvements here and there).

Most of the feature calculators in `tsfresh` (and especially the ones you have mentioned) *do not care about the time column*. More explicitly, they only see the timeseries as a list of values.
This means if you look into the dataframe you have produced:
```python
>>> timeseries
    id  time kind  value
0    1     0    x    9.0
1    1     1    x    9.0
2    1     2    x    9.0
3    1     3    x    7.0
4    2     0    x    1.0
5    2     1    x    1.0
6    2     2    x    2.0
7    1     0    y    9.0
10   1     3    y    7.0
11   2     0    y    1.0
13   2     2    y    2.0
```
and look at the "y" series, the first one is treated as `[9, 7]` and the second one as `[1, 2]` - which also explains why you think the NaN values are treated as if they would never exist: they actually never exist for `tsfresh`.

Now you can (of course) ask: why this design choice? The "problem" is, that there are many different ways to re-sample a time series (and it also depends on if your time is actual clock time or more general "time", e.g. location, frequency etc.) and there exist already many libraries to solve this problem (e.g. pandas has some build-in re-samping methods). That is why we do not try to give additional methods for this, but "just use what the user gives us". Additionally, many of the feature calculators are actually independent on the time axis. Actually, `tsfresh` can even work without a time column at all. That is also the reason why it is called `column_sort` (we just use it for sorting). 

So to answer your specific questions:
* no, it is not a bug and you should impute your time series 
* shall we improve our FAQ: definitely. Shall we strengthen the concept, that most of the feature calculators do not use the time column? Would that help?
* memory-efficiency: you might be correct (even though we would then definitely loose on the computation side - and I actually think we would need to calculate the full, resampled data for some of the feature calculators, which are not as simple as "mean" or "sum", anyways - so I do not think we can really benefit here). As this is a quite large re-design, I am a bit hesitant to say "yes" because I am not sure about the memory benefit already. Also, as a side note, it could be the case that most ML methods using the extracted features can get along with these differences quite well.

Just to wrap it up: I think the confusion comes from the fact, that we do not fill in the NaN values at all (and this part can be improved in our docu) - but if the user gives us a time series with the values `[1, 2, 3]` it is treated as exactly this (no matter what the index says).

Does this help you?

**Comment by cbows** [comment]
Thank you very much for the detailed answer!
I guess the most confusion really came from the fact that `time` is never considered during feature extraction except for sorting and that could maybe be strengthened in the docs. However, given that fact, the results totally make sense.
I also agree that an interpolation strategy would only benefit a couple of features and the non-trivial re-design of the feature calculators would probably not be worth it.
For now I am using Dask to parallelize the feature extraction and split my pipeline so I never have to keep the entire data in memory.

I am happy to close this issue, thanks!
