### ISSUE TITLE
Should I add Root-Mean-Square as a separate feature?

### ISSUE THREAD

**Issue by OliEfr** [blue-yonder/tsfresh#811]
RMS is a useful feature in some domains - in my case for remaining useful life prediction in predictive maintenance.

So I am using this feature on a regular basis. Should I add a RMS calculation as a feature to the tsfresh package (and create a PR)?

EDIT: I just saw, that RMS can be derived from other features (namely `absolut_energy `and `length`.) Should it stay like that or should we add a specific RMS feature on the basis of these both? I would prefer to have a RMS feature.

**Comment by nils-braun** [comment]
Hi @OliEfr and thanks for the issue!
Seems like a good idea and should not add to the computation time significantly (if at all).
We would love to see a PR! Thanks :-)

**Comment by OliEfr** [comment]
Hey thanks for the response @nils-braun 

I started implementation. Obviously, implementing the RMS is not too hard.

However, I have some problems with your frame work. I tried to follow your guidelines [here](https://tsfresh.readthedocs.io/en/latest/text/how_to_contribute.html)

There are a few things, which dont work for me:

1. With `pip install ..`. I get the error: `ERROR: Could not find a version that satisfies the requirement pandas>=0.25.0`. When I use pip3 it works.
2. After installing everything with pip3 I tried to run the tests, but I get the warning `Coverage.py warning: Couldn't parse Python file 'C:\Users\Oliver\Desktop\tsfresh\tsfresh\feature_extraction\data.py' (couldnt-parse)` and `tError while importing test module 'C:\Users\OliEfr\Desktop\tsfresh\tests\integrations\test_bindings.py'` for pretty much any module.
3. I also got errors trying to build the docs. `WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'http://sphinx.pocoo.org/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 400 Client Error: Bad Request for url: http://sphinx.pocoo.org/objects.inv` and also import errors for all modules `autodoc: failed to import module u'tsfresh'; the following exception was raised:
No module named abc`

**Comment by nils-braun** [comment]
Thanks for raising all those issues!
Let me walk through them one by one :-)
1. tsfresh (as most python libraries out there currently) do not run on python 2.* anymore. I would suggest you do not rely on the python version and environment installed by your OS, but you use conda or at least pyenv (if you are not already doing so). I would actually recommend conda (`conda create -n tsfresh python=3.8 pip && conda activate tsfresh`), but that is a matter of choice (and is not related to tsfresh). Your "pip" is probably python 2, so there will not be any of the dependencies still working for it.
2. How did you run the tests? With `pytest`? Could you check with `which pytest` (if you are running a UNIX) where the pytest came from? Did you run with python2 or 3?
3. Probably same question :-) Did you use python 2 or python 3? The warning is fine, the error is probably due to python 2 <-> 3 problems.

I just did the following with conda and it worked:
```bash
conda create -n tsfresh python=3.8 pip
conda activate tsfresh
# check pip
which pip
pip install -r requirements.txt
pip install -r rdocs-requirements.txt
pip install -r test-requirements.txt
pip install -e .
which pytest
pytest tests
python setup.py docs
```

**Comment by OliEfr** [comment]
Just tested it out the way you described. Seems to work fine - mistake was definetely on my side. Thanks for the help!
I'll keep working on it and create a PR asap :)

**Comment by nils-braun** [comment]
Thanks for keep trying!
