### ISSUE TITLE
Compatibility issue with statsmodels 0.18.0

### ISSUE THREAD

**Issue by wjsi** [blue-yonder/tsfresh#897]
**The problem**:

Since v0.18.0, statsmodels stops supporting `unbiased` and uses `adjusted` (https://github.com/statsmodels/statsmodels/commit/3d6c3884b9804842ff039c8c5d63a9ccf519867a#diff-771ed9ae3d316dec0997427f2182d015dbfdaf6935335428bbf177ce1968bc72), and use of `statsmodels.tsa.stattools.acf` in `tsfresh.feature_extraction.ceature_calculators` now causes `TypeError`. We need to use `adjusted` instead of `unbiased` in calls for `acf` in statsmodels later than v0.14.0.

**Comment by fkiraly** [comment]
you mean 0.13.0, right? The update on Friday that also broke `sktime` since it depende on `tsfresh`?

See https://github.com/alan-turing-institute/sktime/issues/1478

We just verified that indeed reverting to 0.12.1 seems to resolve the issue (temporarily).

The fix in `tsfresh` would be to change the name of the argument.

**Comment by MassEast** [comment]
On 0.11 everything works fine.

**Comment by VGODIE** [comment]
I am really looking forward to this update ! Are there any changes happened?

**Comment by kempa-liehr** [comment]
@SirJohnFranklin, thanks for the short demo of the new interface.
