### ISSUE TITLE
Can't get Time-Based Custom Feature to Work

### ISSUE THREAD

**Issue by cogerk** [blue-yonder/tsfresh#996]
**Time Based Custom Feature**:

I was trying to follow this section of the docs and test out the example code provided with the robot dataset, but I couldn't get it to work.  Am I missing something important about how this code works?

When running the following returns an empty dataframe for me, but I'm expecting it to return a dataframe with column `F_x__timespan`

```
from tsfresh.feature_extraction import feature_calculators

@feature_calculators.set_property("input", "pd.Series")
@feature_calculators.set_property("index_type", pd.DatetimeIndex)
def timespan(x):
    ix = x.index

    # Get differences between the last timestamp and the first timestamp in seconds,
    # then convert to hours.
    times_seconds = (ix[-1] - ix[0]).total_seconds()
    return times_seconds / float(3600)


setattr(feature_calculators, timespan.__name__, timespan)


from tsfresh.examples.robot_execution_failures import download_robot_execution_failures, \
    load_robot_execution_failures
from tsfresh import extract_features

download_robot_execution_failures()
timeseries, y = load_robot_execution_failures()

kind_to_fc_parameters = {
    'F_x' :{"timespan":None},
}

extract_features(timeseries, column_id="id", column_sort="time", kind_to_fc_parameters=kind_to_fc_parameters)

```

Please let me know if I can provide any additional info, thanks!

**Environment**:

- Python version:
- Operating System: WSL Ubuntu-20.04 in a docker container
- tsfresh version: tslearn==0.5.2
- Install method: pip

**Comment by nils-braun** [comment]
Hi @cogerk - sorry for the delayed answer.
Two comments on your code:
* starting with tsfresh version 0.19.0, the preferred way to use custom feature extractors is now to put them into the settings dict as keys instead of adding them to the module, like
   ```python
   kind_to_fc_parameters = {
      'F_x' :{timespan: None},
   }
   ```
   (notice the missing " around the timespan). You should not need to use 
   ```python
   setattr(feature_calculators, timespan.__name__, timespan)
   ```
   anymore.
* You are explicitly requesting that your feature calculator can only run on a timeseries with a `DateTimeIndex` (this is what `@feature_calculators.set_property("index_type", pd.DatetimeIndex)` does). The example data `load_robot_execution_failures` however do not have such an index. Maybe try with this data:
   ```python
   timeseries = pd.DataFrame({"col": [1, 2, 3], "id": [1, 1, 1]}, index=pd.date_range("2022-01-01", "2022-01-03"))

   kind_to_fc_parameters = {
       'col' :{timespan: None},
   }

   extract_features(timeseries, column_id="id", kind_to_fc_parameters=kind_to_fc_parameters)
   ```

**Comment by nils-braun** [comment]
Closing for now. Please tell us if you still have questions :)

**Comment by cogerk** [comment]
Thanks very much @nils-braun! Your comments helped immensely.
